// any.js 0.0.1 (a7418f9)
// (c) 2011 Philip Lehmann, Lukas Westermann, at-point ag
// any.js is freely distributable under the MIT license.
// Portions of any.js are inspired or borrowed from Underscore.js,
// Prototype and jQuery.
// For all details and documentation:
// TODO: gh-pages
(function(){var f=this.document!=undefined?this.document:this,c={};this.$a=c;c.VERSION="0.0.1";c.ready=function(a){document.addEventListener("DOMContentLoaded",a,false)};c.css=function(a,b){for(var d in b)a.style[d]=b[d]};c.first=function(a,b){a=b?a:f;return a.querySelector(b||a)};c.all=function(a,b){a=b?a:f;return a.querySelectorAll(b||a)};c.id=function(a,b){a=b?a:f;return a.getElementById(b||a)};c.isFunc=function(a){return typeof a==="function"};c.isObj=function(){};c.isArr=function(){};c.isStr=
function(){};c.isInt=function(){};c.extend=function(){};c.bind=function(a,b,d,e){a.addEventListener(b,d,e)};c.unbind=function(){};c.data=function(a,b,d){if(d!=undefined)a.setAttribute("data-"+b,d);else return a.getAttribute("data-"+b)};c.animate=function(a,b,d,e){if(b.property!=undefined){a.style.webkitTransitionProperty=b.property;a.style.mozTransitionProperty=b.property}if(b.duration!=undefined){a.style.webkitTransitionDuration=b.duration;a.style.mozTransitionDuration=b.duration}if(b.timingFunction!=
undefined){a.style.webkitTransitionTimingFunction=b.timingFunction;a.style.mozTransitionTimingFunction=b.timingFunction}if(b.delay!=undefined){a.style.webkitTransitionDelay=b.delay;a.style.mozTransitionDelay=b.delay}if(e==undefined||e){this.bind(a,"webkitTransitionEnd",this._animationCleanup);this.bind(a,"mozTransitionEnd",this._animationCleanup)}this.css(a,d)};c._animationCleanup=function(a){c.animate(a.currentTarget,{property:null,duration:null,timingFunction:null,delay:null},{},false)};c.html=
function(a){var b=document.createElement("div");b.innerHTML=a;return b.childNodes};c.css.add=function(a,b){if(!a.classList)a.classList=new this.ClassList(a);return a.classList.add(b)};c.css.remove=function(a,b){if(!a.classList)a.classList=new this.ClassList(a);return a.classList.remove(b)};c.css.has=function(a,b){if(!a.classList)a.classList=new this.ClassList(a);return a.classList.contains(b)};c.css.toggle=function(a,b){if(!a.classList)a.classList=new this.ClassList(a);return a.classList.toggle(b)};
c.css.ClassList=function(a){this.node=a;if(!this.node.className)this.node.className="";this.list=a.className.split(" ");this.add=function(b){if(!this.contains(b)){this.list.push(b);this.clean();this.node.className=this.list.join(" ")}};this.remove=function(b){if(this.contains(b)){this.list.splice(this.list.indexOf(b),1);this.clean();this.node.className=this.list.join(" ")}};this.contains=function(b){return this.list.indexOf(b)!==-1?true:false};this.toggle=function(b){this.contains(b)?this.remove(b):
this.add(b)};this.clean=function(){for(var b=[],d=0;d<this.list.length;d++)this.list[d].length>0&&b.push(this.list[d]);this.list=b};this.clean()}})();
