// any.js 0.0.1 (rev:6106982)
// (c) 2011 Philip Lehmann, Lukas Westermann, at-point ag
// any.js is freely distributable under the MIT license.
// Portions of any.js are inspired or borrowed from Underscore.js,
// Prototype and jQuery.
// For all details and documentation:
// TODO: gh-pages
(function(){var f=this.document!=undefined?this.document:this,c={};this.$a=c;c.VERSION="0.0.1";c.ready=function(a){this.bind("DOMContentLoaded",a,false)};c.isFunc=function(a){return typeof a==="function"};c.isObj=function(a){return!Array.isArray(a)&&typeof a==="object"};c.isArr=function(a){return Array.isArray(a)};c.isStr=function(a){return typeof a==="string"};c.extend=function(a,b){for(var d in b)try{a[d]=c.isObj(b[d])?c.extend(a[d],b[d]):b[d]}catch(e){a[d]=b[d]}return a};c.bindHandler=null;c.registerBindHandler=
function(a){c.bindHandler=a};c.json=function(a){if(this.isStr(a))return JSON.parse(a);return JSON.stringify(a)};c.bind=function(a,b,d,e){c.bindHandler!=null?c.bindHandler.bind(a,b,d,e):a.addEventListener(b,d,e)};c.unbind=function(a,b,d,e){c.bindHandler!=null?c.bindHandler.unbind(a,b,d,e):a.removeEventListener(b,d,e)};c.id=function(a,b){a=b?a:f;return a.getElementById(b||a)};c.first=function(a,b){a=b?a:f;return a.querySelector(b||a)};c.all=function(a,b){a=b?a:f;return a.querySelectorAll(b||a)};c.html=
function(a){var b=document.createElement("div");b.innerHTML=a;return b.childNodes};c.data=function(a,b,d){if(d!=undefined)a.setAttribute("data-"+b,d);else return a.getAttribute("data-"+b)};c.css=function(a,b){for(var d in b)a.style[d]=b[d]};c.addClass=function(a,b){if(!a.classList)a.classList=new this._ClassList(a);return a.classList.add(b)};c.removeClass=function(a,b){if(!a.classList)a.classList=new this._ClassList(a);return a.classList.remove(b)};c.hasClass=function(a,b){if(!a.classList)a.classList=
new this._ClassList(a);return a.classList.contains(b)};c.toggleClass=function(a,b){if(!a.classList)a.classList=new this._ClassList(a);return a.classList.toggle(b)};c.animate=function(a,b,d,e,g){if(b.property!=undefined){a.style.webkitTransitionProperty=b.property;a.style.mozTransitionProperty=b.property}if(b.duration!=undefined){a.style.webkitTransitionDuration=b.duration;a.style.mozTransitionDuration=b.duration}if(b.timingFunction!=undefined){a.style.webkitTransitionTimingFunction=b.timingFunction;
a.style.mozTransitionTimingFunction=b.timingFunction}if(b.delay!=undefined){a.style.webkitTransitionDelay=b.delay;a.style.mozTransitionDelay=b.delay}if(e==undefined||e){this.bind(a,"webkitTransitionEnd",this._animationCleanup);this.bind(a,"mozTransitionEnd",this._animationCleanup)}if(c.isFunc(g)){this.bind(a,"webkitTransitionEnd",g);this.bind(a,"mozTransitionEnd",g)}this.css(a,d)};c._animationCleanup=function(a){c.animate(a.currentTarget,{property:null,duration:null,timingFunction:null,delay:null},
{},false)};c.transform=function(a,b,d,e,g){if(a!=undefined){if(this.isStr(b)&&d===undefined){if(a.matrix==undefined)a.matrix={};switch(b){case "translate":if(a.matrix.translate==undefined)a.matrix.translate={x:undefined,y:undefined,z:undefined};return a.matrix.translate;case "scale":if(a.matrix.scale==undefined)a.matrix.scale={x:undefined,y:undefined,z:undefined};return a.matrix.scale;case "rotate":if(a.matrix.rotate==undefined)a.matrix.rotate={x:undefined,y:undefined,z:undefined};return a.matrix.rotate}}else{if(!this.isObj(a.matrix))a.matrix=
{};if(a.matrix.translate==undefined)a.matrix.translate={};if(a.matrix.scale==undefined)a.matrix.scale={};if(a.matrix.rotate==undefined)a.matrix.rotate={};switch(b){case "translate":if(d!=undefined)a.matrix.translate.x=d;if(e!=undefined)a.matrix.translate.y=e;if(g!=undefined)a.matrix.translate.z=g;break;case "scale":if(d!=undefined)a.matrix.scale.x=d;if(e!=undefined)a.matrix.scale.y=e;if(g!=undefined)a.matrix.scale.z=g;break;case "rotate":if(d!=undefined)a.matrix.rotate.x=d;if(e!=undefined)a.matrix.rotate.y=
e;if(g!=undefined)a.matrix.rotate.z=g}b=(a.matrix.translate.x!=undefined&&a.matrix.translate.y!=undefined?"translate("+a.matrix.translate.x+"px,"+a.matrix.translate.y+"px)":"")+" "+(a.matrix.rotate.x!=undefined?"rotate("+a.matrix.rotate.x+"deg)":"")+" "+(a.matrix.scale.x!=undefined?"scale("+a.matrix.scale.x+")":"");a.style.webkitTransform=b;a.style.MozTransform=b}return null}};c._ClassList=function(a){this.node=a;if(!this.node.className)this.node.className="";this.list=a.className.split(" ");this.add=
function(b){if(!this.contains(b)){this.list.push(b);this.clean();this.node.className=this.list.join(" ")}};this.remove=function(b){if(this.contains(b)){this.list.splice(this.list.indexOf(b),1);this.clean();this.node.className=this.list.join(" ")}};this.contains=function(b){return this.list.indexOf(b)!==-1?true:false};this.toggle=function(b){this.contains(b)?this.remove(b):this.add(b)};this.clean=function(){for(var b=[],d=0;d<this.list.length;d++)this.list[d].length>0&&b.push(this.list[d]);this.list=
b};this.clean()};c.ajax=function(a){if(a.method==undefined)a.method="GET";if(a.method=="GET"){a.url=a.url+"?"+a.data;a.data=null}var b=new XMLHttpRequest;b.onreadystatechange=function(){if(b.readyState==4)if(b.status==200)c.isFunc(onsuccess)&&onsuccess(b.responseText);else c.isFunc(onerror)&&onerror()};b.open(a.method,a.url,true);b.send(a.data)}})();(function(){var f={};$a.mt=f;f.VERSION="0.0.1";f.bind=function(){};f.unbind=function(){};f.swipe=function(){};$a.registerBindHandler(f)})();(function(){})();
(function(){})();(function(){})();
