// any.core.js 0.0.1 (rev:6ffcdf6)
// (c) 2011 Philip Lehmann, Lukas Westermann, at-point ag
// any.js is freely distributable under the MIT license.
// Portions of any.js are inspired or borrowed from Underscore.js,
// Prototype and jQuery.
// For all details and documentation:
// TODO: gh-pages
(function(g,i){var c={};g.ready(function(){i.registerBindHandler(c,g.FIREFOX)});c._data={};c._sids={};c._streamIds=[];c.bind=function(a,d,b,e,f){f=g.extend(f,{mozCallback:b});d=d.toLowerCase();switch(d){case "touch":g.bind(a,"MozTouchDown",c.touch_start,e);g.bind(a,"MozTouchMove",c.touch_move,e);g.bind(a,"MozTouchUp",c.touch_end,e,f);break;case "touchstart":g.bind(a,"MozTouchDown",c.touchDown,e,f);break;case "touchmove":g.bind(a,"MozTouchMove",c.touchMove,e,f);break;case "touchend":g.bind(a,"MozTouchUp",
c.touchUp,e,f);break;case "touchcancel":g.bind(a,"MozTouchCancel",c.touchCancel,e,f);break;case "gesturestart":c.bind(a,"touchstart",c.gestureStart,e,f);break;case "gesturechange":c.bind(a,"touchmove",c.gestureChange,e,f);break;case "gestureend":c.bind(a,"touchend",c.gestureEnd,e,f);c.bind(a,"touchcancel",c.gestureEnd,e,f);break;default:g.bind(a,d,b,e,f)}};c.unbind=function(a,d,b,e,f){f=g.extend(f,{mozCallback:b});d=d.toLowerCase();switch(d){case "touch":g.unbind(a,"MozTouchDown",c.touch_start,e);
g.unbind(a,"MozTouchMove",c.touch_move,e);g.unbind(a,"MozTouchUp",c.touch_end,e,f);break;case "touchstart":g.unbind(a,"MozTouchDown",c.touchDown,e,f);break;case "touchmove":g.unbind(a,"MozTouchMove",c.touchMove,e,f);break;case "touchend":g.unbind(a,"MozTouchUp",c.touchUp,e,f);break;case "touchcancel":g.unbind(a,"MozTouchCancel",c.touchCancel,e,f);break;case "gesturestart":c.unbind(a,"touchstart",c.gestureStart,e,f);break;case "gesturechange":c.unbind(a,"touchmove",c.gestureChange,e,f);break;case "gestureend":c.unbind(a,
"touchend",c.gestureEnd,e,f);c.unbind(a,"touchcancel",c.gestureEnd,e,f);break;default:g.unbind(a,d,b,e,f)}};c.touch_start=function(a){var d=c.getObjectByNamespace(a.currentTarget,"click");d.count=0;d.event=a};c.touch_move=function(a){c.getObjectByNamespace(a.currentTarget,"click").count++};c.touch_end=function(a,d){var b=c.getObjectByNamespace(a.currentTarget,"click");if(b.count<50&&Math.abs(b.event.pageX-a.pageX)<20&&Math.abs(b.event.pageY-a.pageY)<20)return d.mozCallback(a,d)};c.touchDown=function(a,
d){var b=c.getObjectByNamespace(a.currentTarget,"touch");b.event=a;b.timer=window.setTimeout(c.touchTimerCancel,1E3,b);return d.mozCallback(a,d)};c.touchMove=function(a,d){var b=c.getObjectByNamespace(a.currentTarget,"touch");b.event=a;if(b.timer){window.clearTimeout(b.timer);b.timer=window.setTimeout(c.touchTimerCancel,1E3,b)}return d.mozCallback(a,d)};c.touchUp=function(a,d){var b=c.getObjectByNamespace(a.currentTarget,"touch");if(b.timer){window.clearTimeout(b.timer);b.timer=null}return d.mozCallback(a,
d)};c.touchCancel=function(a,d){var b=c.getObjectByNamespace(a.currentTarget,"touch");if(b.timer){window.clearTimeout(b.timer);b.timer=null}return d.mozCallback(a,d)};c.touchTimerCancel=function(){};c.sidCleanup=function(a){if(c._sids[a]){var d=c.getObjectByNamespace(c._sids[a],"gesture");if(d){delete d.paths[a];delete c._sids[a]}}};c.gestureStart=function(a,d){var b=c.getObjectByNamespace(a.currentTarget,"gesture");c.sidCleanup(a.streamId);c._sids[a.streamId]=a.currentTarget;if(b.paths==undefined)b.paths=
{};b.paths[a.streamId]=[];b.paths[a.streamId].push([a.pageX,a.pageY]);var e=[],f;for(f in b.paths)e.push(f);if(e.length>1){e=c._calculate_for_event(b.paths[e[0]],b.paths[e[1]],b);if(e.scale!=b.scale||e.rotation!=b.rotation){b.scale=a.scale=e.scale;b.rotation=a.rotation=e.rotation;return d.mozCallback(a,d)}}};c.gestureChange=function(a,d){var b=c.getObjectByNamespace(a.currentTarget,"gesture");if(!c._sids[a.streamId])c._sids[a.streamId]=a.currentTarget;if(b.paths==undefined)b.paths={};if(b.paths[a.streamId]==
undefined)b.paths[a.streamId]=[];b.paths[a.streamId].push([a.pageX,a.pageY]);var e=[],f;for(f in b.paths)e.push(f);if(e.length>1){e=c._calculate_for_event(b.paths[e[0]],b.paths[e[1]],b);if(e.scale!=b.scale||e.rotation!=b.rotation){b.scale=a.scale=e.scale;b.rotation=a.rotation=e.rotation;return d.mozCallback(a,d)}}};c.gestureEnd=function(a,d){var b=c.getObjectByNamespace(a.currentTarget,"gesture");if(!c._sids[a.streamId])c._sids[a.streamId]=a.currentTarget;if(b.paths==undefined)b.paths={};b.paths[a.streamId]=
[];b.paths[a.streamId].push([a.pageX,a.pageY]);var e=[],f;for(f in b.paths)e.push(f);if(e.length>1){e=c._calculate_for_event(b.paths[e[0]],b.paths[e[1]],b);if(e.scale!=b.scale||e.rotation!=b.rotation){b.scale=a.scale=e.scale;b.rotation=a.rotation=e.rotation;c.sidCleanup(a.streamId);return d.mozCallback(a,d)}}c.sidCleanup(a.streamId)};c.getObjectByNamespace=function(a,d){if(!a.mozTouch)a.mozTouch={};a.mozTouch[d]||(a.mozTouch[d]={});return a.mozTouch[d]};c._q=function(a,d){if(a<0&&d>0)return 1;else if(a<
0&&d<0)return 2;else if(a>0&&d<0)return 3;return 0};c._calculate_for_event=function(a,d,b){var e=d[0][0]-a[0][0],f=d[0][1]-a[0][1];if(b.rotationCalc==undefined){a=Math.sqrt(e*e+f*f);b.rotationCalc={sqrt:a,arc_eh:Math.acos(f/a)};return{rotation:0,scale:1}}var j=d[d.length-1][0]-a[a.length-1][0];d=d[d.length-1][1]-a[a.length-1][1];a=Math.sqrt(j*j+d*d);f=Math.acos((e*j+f*d)/(b.rotationCalc.sqrt*a))/0.017453292519943295;var h=b.rotationCalc.arc_eh,k=0;k=e>=0?j*Math.cos(h)-d*Math.sin(h):j*Math.cos(h)+
d*Math.sin(h);if(k>0)f*=-1;scale=a/b.rotationCalc.sqrt;if(isNaN(f))f=0;if(isNaN(scale))scale=0;return{rotation:f,scale:scale}}})(this._anyNoConflict,this._anyMtNoConflict);
(function(g){var i={};this.$mt=this._anyMtNoConflict=i;i.VERSION="0.0.1";i.bindHandler={};i.registerBindHandler=function(a,d){this.bindHandler[d]=a};i.unregsiterBindHandler=function(a){delete this.bindHandler[a]};i.bind=function(a,d,b,e,f){var j=g.browserDetection();if(!g.isArr(a)&&!g.isCol(a))a=[a];for(var h=0;h<a.length;h++)this.bindHandler[j]?this.bindHandler[j].bind(a[h],d,b,e,f):c.bind(a[h],d,b,e,f)};i.unbind=function(a,d,b,e,f){var j=g.browserDetection();if(!g.isArr(a)&&!g.isCol(a))a=[a];for(var h=
0;h<a.length;h++)this.bindHandler[j]?this.bindHandler[j].unbind(a[h],d,b,e,f):c.unbind(a[h],d,b,e,f)};i.swipe=function(){};i.escapeElement=function(a){a.onclick=function(){return false};a.onmousedown=function(){document.getElementById("focusmaker").focus();return false};a.onmousemove=function(){return false};a.onmouseup=function(){return false};a.onmouseover=function(){return false};a.onmouseout=function(){return false};a.onmouseenter=function(){return false};a.onmouseleave=function(){return false}};
var c={_mapping:{touch:"click",touchstart:"mousedown",touchmove:"mousemove",touchend:"mouseup"},bind:function(a,d,b,e,f){return this._mapping[d]!==undefined?g.bind(a,this._mapping[d],b,e,f):g.bind(a,d,b,e,f)},unbind:function(a,d,b,e,f){return this._mapping[d]!==undefined?g.unbind(a,this._mapping[d],b,e,f):g.unbind(a,d,b,e,f)}}})(this._anyNoConflict);
