// any.core.js 0.0.1 (rev:6ffcdf6)
// (c) 2011 Philip Lehmann, Lukas Westermann, at-point ag
// any.js is freely distributable under the MIT license.
// Portions of any.js are inspired or borrowed from Underscore.js,
// Prototype and jQuery.
// For all details and documentation:
// TODO: gh-pages
(function(){var h=this.document?this.document:this,f={};this.$a=this._anyNoConflict=f;f.VERSION="0.0.1";f.ready=function(a){this.bind(document,"DOMContentLoaded",a,false)};f.CHROME="chrome";f.FIREFOX="firefox";f.FENNEC="fennec";f.SAFARI="safari";f.MOBILE_SAFARI="mobile_safari";f._BROWSERS={};f._BROWSERS[f.CHROME]=/chrome.*safari/gi;f._BROWSERS[f.FIREFOX]=/Firefox\/4/gi;f._BROWSERS[f.FENNEC]=/fennec/gi;f._BROWSERS[f.SAFARI]=/version.*safari/gi;f._BROWSERS[f.MOBILE_SAFARI]=/version.*mobile.*safari/gi;
f.browserDetection=function(){for(var a in this._BROWSERS)if(this.isBrowser(a))return a;return false};f.isBrowser=function(a){return navigator.userAgent.match(f._BROWSERS[a])!==null};f.isFunc=function(a){return typeof a==="function"};f.isObj=function(a){return!Array.isArray(a)&&typeof a==="object"};f.isArr=function(a){return Array.isArray(a)};f.isCol=function(a){return a instanceof NodeList||a instanceof HTMLCollection};f.isStr=function(a){return typeof a==="string"};f.extend=function(a,b){if(a==
undefined)a={};for(var c in b)try{a[c]=f.isObj(b[c])?f.extend(a[c],b[c]):b[c]}catch(d){a[c]=b[c]}return a};f.json=function(a){if(this.isStr(a))return JSON.parse(a);return JSON.stringify(a)};f.ready=function(a){if(h.addEventListener)h.addEventListener("DOMContentLoaded",a,false);else if(h.readyState&&h.readyState==="complete")a();else h.readyState&&h.attachEvent?h.attachEvent("onreadystatechange",function(){h.readyState==="complete"&&a()}):f.bind(h,"load",a)};f.bind=function(a,b,c,d,e){d=d!==true?
false:true;if(this.isArr(a)||this.isCol(a))for(var g=0;g<a.length;g++)this.bind(a[g],b,c,d,e);else if(this.isFunc(a.addEventListener))return e?a.addEventListener(b,function(i){return c(i,e)},d):a.addEventListener(b,c,d);else if(this.isFunc(a.attachEvent))return e?a.attachEvent("on"+b,function(i){return c(i,e)}):a.attachEvent("on"+b,c)};f.unbind=function(a,b,c,d,e){d=d!==true?false:true;if(this.isArr(a)||this.isCol(a))for(var g=0;g<a.length;g++)this.unbind(a[g],b,c,d);else if(this.isFunc(a.removeEventListener))return e?
a.removeEventListener(b,function(i){return c(i,e)},d):a.removeEventListener(b,c,d);else if(this.isFunc(a.detachEvent))return e?a.detachEvent("on"+b,function(i){return c(i,e)}):a.detachEvent("on"+b,c)};f._supportsEvent=function(a,b){b=b||document.createElement("div");return"on"+a in b};f.id=function(){return(arguments.length>1?arguments[0]:h).getElementById(arguments.length>1?arguments[1]:arguments[0])};f.elsByClass=function(){return(arguments.length>1?arguments[0]:h).getElementsByClassName(arguments.length>
1?arguments[1]:arguments[0])};f.elsByTag=function(a,b){a=arguments.length>1?arguments[0]:h;b=arguments.length>1?arguments[1]:arguments[0];return a.getElementsByTagName(b)};f.first=function(){var a=arguments.length>1?arguments[0]:h,b=arguments.length>1?arguments[1]:arguments[0];if(this.isFunc(a.querySelector))return a.querySelector(b);else if(this.isFunc(Sizzle)){a=Sizzle(b,a);if(a.length>0)return a[0];return null}};f.all=function(){var a=arguments.length>1?arguments[0]:h,b=arguments.length>1?arguments[1]:
arguments[0];if(this.isFunc(a.querySelectorAll))return a.querySelectorAll(b);else if(this.isFunc(Sizzle))return Sizzle(b,a)};f.html=function(a){var b=document.createElement("div");b.innerHTML=a;return b.childNodes};f.data=function(a,b,c){if(c!=undefined)if(a.dataset)a.dataset[b]=c;else a.setAttribute("data-"+b,c);else return a.dataset?a.dataset[b]:a.getAttribute("data-"+b)};f.css=function(a,b){if(this.isArr(a)||this.isCol(a))for(var c=0;c<a.length;c++)this.css(a[c],b);else for(c in b)a.style[c]=b[c]};
f.show=function(a){this.css(a,{display:""})};f.hide=function(a){this.css(a,{display:"none"})};f.toggle=function(a){if(this.isArr(a)||this.isCol(a))for(var b=0;b<a.length;b++)this.toggle(a[b]);else a.style.display=="none"?this.show(a):this.hide(a)};f.addClass=function(a,b){if(this.isArr(a)||this.isCol(a))for(var c=0;c<a.length;c++)this.addClass(a[c],b);else{if(!a.classList)a.classList=new this._ClassList(a);return a.classList.add(b)}};f.removeClass=function(a,b){if(this.isArr(a)||this.isCol(a))for(var c=
0;c<a.length;c++)this.removeClass(a[c],b);else{if(!a.classList)a.classList=new this._ClassList(a);return a.classList.remove(b)}};f.hasClass=function(a,b){if(!a.classList)a.classList=new this._ClassList(a);return a.classList.contains(b)};f.toggleClass=function(a,b){if(this.isArr(a)||this.isCol(a))for(var c=0;c<a.length;c++)this.toggleClass(a[c],b);else{if(!a.classList)a.classList=new this._ClassList(a);return a.classList.toggle(b)}};f.animate=function(a,b,c,d,e){if(this.isArr(a)||this.isCol(a))for(var g=
0;g<a.length;g++)this.animate(a[g],b,c,d,e);else{if(b.property!=undefined){a.style.webkitTransitionProperty=b.property;a.style.mozTransitionProperty=b.property}if(b.duration!=undefined){a.style.webkitTransitionDuration=b.duration;a.style.mozTransitionDuration=b.duration}if(b.timingFunction!=undefined){a.style.webkitTransitionTimingFunction=b.timingFunction;a.style.mozTransitionTimingFunction=b.timingFunction}if(b.delay!=undefined){a.style.webkitTransitionDelay=b.delay;a.style.mozTransitionDelay=b.delay}if(d==
undefined||d){this.bind(a,"webkitTransitionEnd",this._animationCleanup);this.bind(a,"mozTransitionEnd",this._animationCleanup)}if(f.isFunc(e)){this.bind(a,"webkitTransitionEnd",e);this.bind(a,"mozTransitionEnd",e)}this.css(a,c)}};f._animationCleanup=function(a){f.animate(a.currentTarget,{property:null,duration:null,timingFunction:null,delay:null},{},false)};f.transform=function(a,b,c,d,e,g){if(a!=undefined)if(this.isStr(b)&&c===undefined){if(a.matrix==undefined)a.matrix={};switch(b){case "translate":if(a.matrix.translate==
undefined)a.matrix.translate={x:undefined,y:undefined,z:undefined};return a.matrix.translate;case "scale":if(a.matrix.scale==undefined)a.matrix.scale={x:undefined,y:undefined,z:undefined};return a.matrix.scale;case "rotate":if(a.matrix.rotate==undefined)a.matrix.rotate={x:undefined,y:undefined,z:undefined};return a.matrix.rotate}return null}else{if(!this.isObj(a.matrix))a.matrix={};if(a.matrix.translate==undefined)a.matrix.translate={};if(a.matrix.scale==undefined)a.matrix.scale={};if(a.matrix.rotate==
undefined)a.matrix.rotate={};switch(b){case "translate":if(c!=undefined)a.matrix.translate.x=c;if(d!=undefined)a.matrix.translate.y=d;if(e!=undefined)a.matrix.translate.z=e;break;case "scale":if(c!=undefined)a.matrix.scale.x=c;if(d!=undefined)a.matrix.scale.y=d;if(e!=undefined)a.matrix.scale.z=e;break;case "rotate":if(c!=undefined)a.matrix.rotate.x=c;if(d!=undefined)a.matrix.rotate.y=d;if(e!=undefined)a.matrix.rotate.z=e}b=(a.matrix.translate.x!=undefined&&a.matrix.translate.y!=undefined?"translate("+
a.matrix.translate.x+"px,"+a.matrix.translate.y+"px)":"")+" "+(a.matrix.rotate.x!=undefined?"rotate("+a.matrix.rotate.x+"deg)":"")+" "+(a.matrix.scale.x!=undefined?"scale("+a.matrix.scale.x+")":"");if(g!==true){a.style.webkitTransform=b;a.style.MozTransform=b;a.style.oTransform=b;a.style.transform=b}else return b}};f._ClassList=function(a){this.node=a;if(!this.node.className)this.node.className="";this.list=a.className.split(" ");this.add=function(b){if(!this.contains(b)){this.list.push(b);this.clean();
this.node.className=this.list.join(" ")}};this.remove=function(b){if(this.contains(b)){this.list.splice(this.list.indexOf(b),1);this.clean();this.node.className=this.list.join(" ")}};this.contains=function(b){return this.list.indexOf(b)!==-1?true:false};this.toggle=function(b){this.contains(b)?this.remove(b):this.add(b)};this.clean=function(){for(var b=[],c=0;c<this.list.length;c++)this.list[c].length>0&&b.push(this.list[c]);this.list=b};this.clean()};f.ajax=function(a){if(a.method==undefined)a.method=
"GET";if(this.isObj(a.data)&&a.data!=undefined){var b=[],c;for(c in a.data)b.push(c+"="+encodeURIComponent(a.data[c]));a.data=b.join("&")}if(a.method=="GET"&&a.data!=undefined){a.url=a.url+"?"+a.data;a.data=null}var d=new XMLHttpRequest;d.onreadystatechange=function(){if(d.readyState==4)if(d.status==200){if(f.isFunc(a.onsuccess))a.onsuccess(d)}else if(f.isFunc(a.onerror))a.onerror(d)};d.open(a.method,a.url,true);d.send(a.data)}})();
(function(h,f){var a={};h.ready(function(){f.registerBindHandler(a,h.FIREFOX)});a._data={};a._sids={};a._streamIds=[];a.bind=function(b,c,d,e,g){g=h.extend(g,{mozCallback:d});c=c.toLowerCase();switch(c){case "touch":h.bind(b,"MozTouchDown",a.touch_start,e);h.bind(b,"MozTouchMove",a.touch_move,e);h.bind(b,"MozTouchUp",a.touch_end,e,g);break;case "touchstart":h.bind(b,"MozTouchDown",a.touchDown,e,g);break;case "touchmove":h.bind(b,"MozTouchMove",a.touchMove,e,g);break;case "touchend":h.bind(b,"MozTouchUp",
a.touchUp,e,g);break;case "touchcancel":h.bind(b,"MozTouchCancel",a.touchCancel,e,g);break;case "gesturestart":a.bind(b,"touchstart",a.gestureStart,e,g);break;case "gesturechange":a.bind(b,"touchmove",a.gestureChange,e,g);break;case "gestureend":a.bind(b,"touchend",a.gestureEnd,e,g);a.bind(b,"touchcancel",a.gestureEnd,e,g);break;default:h.bind(b,c,d,e,g)}};a.unbind=function(b,c,d,e,g){g=h.extend(g,{mozCallback:d});c=c.toLowerCase();switch(c){case "touch":h.unbind(b,"MozTouchDown",a.touch_start,e);
h.unbind(b,"MozTouchMove",a.touch_move,e);h.unbind(b,"MozTouchUp",a.touch_end,e,g);break;case "touchstart":h.unbind(b,"MozTouchDown",a.touchDown,e,g);break;case "touchmove":h.unbind(b,"MozTouchMove",a.touchMove,e,g);break;case "touchend":h.unbind(b,"MozTouchUp",a.touchUp,e,g);break;case "touchcancel":h.unbind(b,"MozTouchCancel",a.touchCancel,e,g);break;case "gesturestart":a.unbind(b,"touchstart",a.gestureStart,e,g);break;case "gesturechange":a.unbind(b,"touchmove",a.gestureChange,e,g);break;case "gestureend":a.unbind(b,
"touchend",a.gestureEnd,e,g);a.unbind(b,"touchcancel",a.gestureEnd,e,g);break;default:h.unbind(b,c,d,e,g)}};a.touch_start=function(b){var c=a.getObjectByNamespace(b.currentTarget,"click");c.count=0;c.event=b};a.touch_move=function(b){a.getObjectByNamespace(b.currentTarget,"click").count++};a.touch_end=function(b,c){var d=a.getObjectByNamespace(b.currentTarget,"click");if(d.count<50&&Math.abs(d.event.pageX-b.pageX)<20&&Math.abs(d.event.pageY-b.pageY)<20)return c.mozCallback(b,c)};a.touchDown=function(b,
c){var d=a.getObjectByNamespace(b.currentTarget,"touch");d.event=b;d.timer=window.setTimeout(a.touchTimerCancel,1E3,d);return c.mozCallback(b,c)};a.touchMove=function(b,c){var d=a.getObjectByNamespace(b.currentTarget,"touch");d.event=b;if(d.timer){window.clearTimeout(d.timer);d.timer=window.setTimeout(a.touchTimerCancel,1E3,d)}return c.mozCallback(b,c)};a.touchUp=function(b,c){var d=a.getObjectByNamespace(b.currentTarget,"touch");if(d.timer){window.clearTimeout(d.timer);d.timer=null}return c.mozCallback(b,
c)};a.touchCancel=function(b,c){var d=a.getObjectByNamespace(b.currentTarget,"touch");if(d.timer){window.clearTimeout(d.timer);d.timer=null}return c.mozCallback(b,c)};a.touchTimerCancel=function(){};a.sidCleanup=function(b){if(a._sids[b]){var c=a.getObjectByNamespace(a._sids[b],"gesture");if(c){delete c.paths[b];delete a._sids[b]}}};a.gestureStart=function(b,c){var d=a.getObjectByNamespace(b.currentTarget,"gesture");a.sidCleanup(b.streamId);a._sids[b.streamId]=b.currentTarget;if(d.paths==undefined)d.paths=
{};d.paths[b.streamId]=[];d.paths[b.streamId].push([b.pageX,b.pageY]);var e=[],g;for(g in d.paths)e.push(g);if(e.length>1){e=a._calculate_for_event(d.paths[e[0]],d.paths[e[1]],d);if(e.scale!=d.scale||e.rotation!=d.rotation){d.scale=b.scale=e.scale;d.rotation=b.rotation=e.rotation;return c.mozCallback(b,c)}}};a.gestureChange=function(b,c){var d=a.getObjectByNamespace(b.currentTarget,"gesture");if(!a._sids[b.streamId])a._sids[b.streamId]=b.currentTarget;if(d.paths==undefined)d.paths={};if(d.paths[b.streamId]==
undefined)d.paths[b.streamId]=[];d.paths[b.streamId].push([b.pageX,b.pageY]);var e=[],g;for(g in d.paths)e.push(g);if(e.length>1){e=a._calculate_for_event(d.paths[e[0]],d.paths[e[1]],d);if(e.scale!=d.scale||e.rotation!=d.rotation){d.scale=b.scale=e.scale;d.rotation=b.rotation=e.rotation;return c.mozCallback(b,c)}}};a.gestureEnd=function(b,c){var d=a.getObjectByNamespace(b.currentTarget,"gesture");if(!a._sids[b.streamId])a._sids[b.streamId]=b.currentTarget;if(d.paths==undefined)d.paths={};d.paths[b.streamId]=
[];d.paths[b.streamId].push([b.pageX,b.pageY]);var e=[],g;for(g in d.paths)e.push(g);if(e.length>1){e=a._calculate_for_event(d.paths[e[0]],d.paths[e[1]],d);if(e.scale!=d.scale||e.rotation!=d.rotation){d.scale=b.scale=e.scale;d.rotation=b.rotation=e.rotation;a.sidCleanup(b.streamId);return c.mozCallback(b,c)}}a.sidCleanup(b.streamId)};a.getObjectByNamespace=function(b,c){if(!b.mozTouch)b.mozTouch={};b.mozTouch[c]||(b.mozTouch[c]={});return b.mozTouch[c]};a._q=function(b,c){if(b<0&&c>0)return 1;else if(b<
0&&c<0)return 2;else if(b>0&&c<0)return 3;return 0};a._calculate_for_event=function(b,c,d){var e=c[0][0]-b[0][0],g=c[0][1]-b[0][1];if(d.rotationCalc==undefined){b=Math.sqrt(e*e+g*g);d.rotationCalc={sqrt:b,arc_eh:Math.acos(g/b)};return{rotation:0,scale:1}}var i=c[c.length-1][0]-b[b.length-1][0];c=c[c.length-1][1]-b[b.length-1][1];b=Math.sqrt(i*i+c*c);g=Math.acos((e*i+g*c)/(d.rotationCalc.sqrt*b))/0.017453292519943295;var j=d.rotationCalc.arc_eh,k=0;k=e>=0?i*Math.cos(j)-c*Math.sin(j):i*Math.cos(j)+
c*Math.sin(j);if(k>0)g*=-1;scale=b/d.rotationCalc.sqrt;if(isNaN(g))g=0;if(isNaN(scale))scale=0;return{rotation:g,scale:scale}}})(this._anyNoConflict,this._anyMtNoConflict);
(function(h){var f={};this.$mt=this._anyMtNoConflict=f;f.VERSION="0.0.1";f.bindHandler={};f.registerBindHandler=function(b,c){this.bindHandler[c]=b};f.unregsiterBindHandler=function(b){delete this.bindHandler[b]};f.bind=function(b,c,d,e,g){var i=h.browserDetection();if(!h.isArr(b)&&!h.isCol(b))b=[b];for(var j=0;j<b.length;j++)this.bindHandler[i]?this.bindHandler[i].bind(b[j],c,d,e,g):a.bind(b[j],c,d,e,g)};f.unbind=function(b,c,d,e,g){var i=h.browserDetection();if(!h.isArr(b)&&!h.isCol(b))b=[b];for(var j=
0;j<b.length;j++)this.bindHandler[i]?this.bindHandler[i].unbind(b[j],c,d,e,g):a.unbind(b[j],c,d,e,g)};f.swipe=function(){};f.escapeElement=function(b){b.onclick=function(){return false};b.onmousedown=function(){document.getElementById("focusmaker").focus();return false};b.onmousemove=function(){return false};b.onmouseup=function(){return false};b.onmouseover=function(){return false};b.onmouseout=function(){return false};b.onmouseenter=function(){return false};b.onmouseleave=function(){return false}};
var a={_mapping:{touch:"click",touchstart:"mousedown",touchmove:"mousemove",touchend:"mouseup"},bind:function(b,c,d,e,g){return this._mapping[c]!==undefined?h.bind(b,this._mapping[c],d,e,g):h.bind(b,c,d,e,g)},unbind:function(b,c,d,e,g){return this._mapping[c]!==undefined?h.unbind(b,this._mapping[c],d,e,g):h.unbind(b,c,d,e,g)}}})(this._anyNoConflict);
